---
# tasks file for python

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [python]

- name: install packages for debian system
  apt: name={{ item }} state=present
  with_items:
    - "{{ main_packages }}"
    - "{{ os_packages }}"
    - "{{ python_package_modules }}"
  when: ansible_os_family=='Debian'
  tags: [python]

- name: install packages for rhel system
  yum: name={{ item }} state=present
  with_items:
    - "{{ main_packages }}"
    - "{{ os_packages }}"
    - "{{ python_package_modules }}"
  when: ansible_os_family=='RedHat'
  tags: [python]

- name: install pip modules
  pip: name={{ item }} state=present
  with_items:
    - "{{ python_pip_modules }}"
  when: python_pip_modules is defined
  tags: [python]
